version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/backend
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/backend
    owner: ubuntu
    group: ubuntu
    
hooks:
  ApplicationStart:
    - location: /scripts/restart.sh
      timeout: 60
      runas: ubuntu
